### ISSUE TITLE
discord.py instead of discord.py-self

### ISSUE THREAD

**Issue by StefCoders** [glizzykingdreko/DiscordWizard#2]
C:\Users\-----\Downloads\DiscordWizard-main\DiscordWizard-main>python server.py
Traceback (most recent call last):
  File "C:\Users\-----\Downloads\DiscordWizard-main\DiscordWizard-main\server.py", line 22, in <module>
    bot = commands.Bot(command_prefix='>', self_bot=True)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: BotBase.__init__() missing 1 required keyword-only argument: 'intents'

**Comment by glizzykingdreko** [comment]
You are using discord.py library instead of discord.py-self==1.9.2 like the requirements.txt asks for

**Comment by StefCoders** [comment]
So fast!

**Comment by StefCoders** [comment]
Traceback (most recent call last):
  File "C:\Users\stefa\Downloads\DiscordWizard-main\DiscordWizard-main\server.py", line 214, in <module>
    bot.loop.run_until_complete(start_server)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\stefa\AppData\Local\Programs\Python\Python311\Lib\site-packages\discord\client.py", line 129, in __getattr__
    raise AttributeError(msg)
AttributeError: loop attribute cannot be accessed in non-async contexts. Consider using either an asynchronous main function and passing it to asyncio.run or using asynchronous initialisation hooks such as Client.setup_hook

**Comment by glizzykingdreko** [comment]
Be sure to run on 1.9.2 of discord.py-self, in case the error persist you may wanna change it into an asyncio loop with something like this

```py
start_server = websockets.serve(websocket_handler, HOST, PORT)
asyncio.get_event_loop().run_until_complete(start_server)
bot.run(TOKEN)
```

**Comment by StefCoders** [comment]
Traceback (most recent call last):
  File "C:\Users\stefa\AppData\Local\Programs\Python\Python311\Lib\site-packages\websockets\legacy\server.py", line 240, in handler
    await self.ws_handler(self)
  File "C:\Users\stefa\AppData\Local\Programs\Python\Python311\Lib\site-packages\websockets\legacy\server.py", line 1186, in _ws_handler
    return await cast(
           ^^^^^^^^^^^
  File "C:\Users\stefa\Downloads\DiscordWizard-main\DiscordWizard-main\server.py", line 148, in websocket_handler
    updated_sitemap = await update_server_structure(data["data"], sitemap_file)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\stefa\Downloads\DiscordWizard-main\DiscordWizard-main\server.py", line 71, in update_server_structure
    webhook = await channel.create_webhook(name=WEBHOOK_NAME)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\stefa\AppData\Local\Programs\Python\Python311\Lib\site-packages\discord\channel.py", line 419, in create_webhook
    data = await self._state.http.create_webhook(self.id, name=str(name), avatar=avatar)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\stefa\AppData\Local\Programs\Python\Python311\Lib\site-packages\discord\http.py", line 302, in request
    raise HTTPException(r, data)
discord.errors.HTTPException: 400 Bad Request (error code: 50035): Invalid Form Body
In name: Username cannot contain "discord"

**Comment by StefCoders** [comment]
When server receives a sitemap after a few seconds.

**Comment by glizzykingdreko** [comment]
U able to provide the sitemap who makes the crash?
