### ISSUE TITLE
Error with 'discord' in name

### ISSUE THREAD

**Issue by eduDev81** [glizzykingdreko/DiscordWizard#5]
Started server.py
Started client.py

All was working smoothly, until....

```
Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.10/site-packages/websockets/legacy/server.py", line 240, in handler
    await self.ws_handler(self)
  File "/opt/homebrew/lib/python3.10/site-packages/websockets/legacy/server.py", line 1186, in _ws_handler
    return await cast(
  File "/Users/tester/Desktop/DiscordWizard-main/server.py", line 148, in websocket_handler
    updated_sitemap = await update_server_structure(data["data"], sitemap_file)
  File "/Users/tester/Desktop/DiscordWizard-main/server.py", line 59, in update_server_structure
    webhook = await channel.create_webhook(name=WEBHOOK_NAME)
  File "/opt/homebrew/lib/python3.10/site-packages/discord/channel.py", line 419, in create_webhook
    data = await self._state.http.create_webhook(self.id, name=str(name), avatar=avatar)
  File "/opt/homebrew/lib/python3.10/site-packages/discord/http.py", line 302, in request
    raise HTTPException(r, data)
discord.errors.HTTPException: 400 Bad Request (error code: 50035): Invalid Form Body
In name: Username cannot contain "discord"
2023-10-11 10:26:13,705 - INFO - connection closed
```

**Comment by glizzykingdreko** [comment]
do the other server got a channel called `discord`?

**Comment by eduDev81** [comment]
mmm no it does not seem to have, not even with `discord` inside any of the channel names

**Comment by glizzykingdreko** [comment]
Can you provide the server sitemap that has been generated?

**Comment by eduDev81** [comment]
not sure how to get it

**Comment by glizzykingdreko** [comment]
it gets created when server.py starts

**Comment by it-drafter** [comment]
The same error happened to me.

This error seems to prevent the sitemap .json file from generating. That's why you couldn't find it.

**Try this:**

Just change the webhook name in the settings.yaml file to something that doesn't contain the word 'discord'.

Incorrect:
webhook_name: DiscordWizard

Correct:
webhook_name: Wizard

I also changed the name of the folder containing this project files from 'DiscordWizard' to 'Wizard', just in case.

Worked for me.
